{"solution_id": "30sep22", "is_enabled": true, "category": "ML", "name": "error_0_9", "description": "", "cts": "2021-07-05T09:34:29.938984", "is_deleted": false, "uts": "2021-07-05T09:34:59.320831", "default_version": "17845704-96fa-416f-b9fc-d06a147f51b7", "created_by": "system", "modified_by": "system", "asset_source": {"type": "", "name": "", "version": ""}, "pulse_enabled": false, "_XpmsObjectMixin__type": "CustomFunction", "_XpmsObjectMixin__api_version": "10.0", "file_name": "error_model_0_9.py", "exec_grp_id": "0c29aec5-3744-45c0-93d5-eccf0f91b227", "dependency_package": "default_dependency_package_group", "is_fork": false, "function_config": [], "source": "default", "function_id": "55762a74-b3ab-48e1-83e1-ae25b44386c5", "resources": [{"dataset": "4cf499dd-729d-4423-8602-09f4e1f63c47", "binaries": ["binaries/d559c9a8-a1bc-4276-8bde-8c9adad66809/core_error_model_0.9.pkl"]}]}